# Generated by Django 3.2.8 on 2021-10-14 05:10

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
    ]
