# Generated by Django 3.2.8 on 2021-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_post_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
