# Generated by Django 3.2.8 on 2021-10-21 16:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'ordering': ('username', 'email', 'first_name', 'last_name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
